name: deepmm
channels:
  - conda-forge
dependencies:
  #
  - pandas
  - tqdm
  - matplotlib
  - pyyaml
  - tabulate
  - pip
  - pip:
    - einops
    - plotly
    - psycopg2-binary
    - optuna
    - redis