PIPELINE:
  name: "market making"
  version: "1.0.0"
  description: "Implementation of Avellaneda-Stoikov's approach"
  params:
    fee: 0.125
    # pipeline parameters
    save_dir: "runs/papertrading"
    is_optimization: False
    maximum_inventory: 100
    
  # Market Making Parameters
    num_of_spread: 0.2
    gamma: 0.2 # risk aversion
    historical_window_size: 0 # number of days used to calculate the historical volatility
    min_second_time_step: 30
    close_at: "14:20:45"
    start_at: "09:00:00"